scripts: cleanup

diff --git a/scripts/.local/bin/cleanup-sources b/scripts/.local/bin/cleanup-sources
--- a/scripts/.local/bin/cleanup-sources
+++ b/scripts/.local/bin/cleanup-sources
@@ -6,6 +6,11 @@ if [ ! -d $HOME/Sources ]; then
     exit 127
 fi
 
+if [[ ! -x "$(command -v tmsu)" ]]; then
+    echo "tmsu: command not found"
+    exit 1
+fi
+
 pushd $HOME/Sources >/dev/null
 
 # Remove `apt-get source` artefacts
@@ -16,5 +21,16 @@ rm -f *.dsc *.asc      \
       *.debian.*gz     \
       *.debian.*bz2    \
       *.debian.*xz
+
+# Find packages downloaded with `apt-get source` that has been tagged as
+# `packages`. I don't want to keep them anymore because they could not be
+# updated with `git pull`.
+for d in `tmsu files packages`; do
+    if [[ -d $d ]]; then
+        if [[ ! -d $d/.git/ ]]; then
+            rm -r $d
+        fi
+    fi
+done
 
 popd >/dev/null
