i3: fixup active-task script

diff --git a/i3/Scripts/i3/active-task b/i3/Scripts/i3/active-task
--- a/i3/Scripts/i3/active-task
+++ b/i3/Scripts/i3/active-task
@@ -1,7 +1,17 @@
-#!/bin/bash
-context=`task rc.gc=off _get rc.context`
-task=`task notify +ACTIVE | sed '4q;d'`
-id=`echo $task | awk '{ print $1 }'`
-desc=`echo $task | awk '{ $1=""; print }'`
+#!/usr/bin/env bash
 
-notify-send "[${id}][${context}]" "${desc}" -i task-due
+if [[ ! -x "$(command -v task)" ]]; then
+    echo "task: command not found"
+    exit 1
+fi
+
+context=`task rc.gc=off _get rc.context`
+if [[ $context != "" ]]; then
+    context="($context)"
+fi
+
+task_body=`task minimal +ACTIVE | sed '4q;d' | awk -F' ' '{ $2=""};1'`
+task_id=`echo $task_body | awk '{ print $1 }'`
+task_desc=`echo $task_body | awk '{ $1=""; print }' | awk '{$1=$1};1'`
+
+notify-send "Active task: ${task_id} ${context}" "${task_desc}" -i task-due
